[DEV-213517] Implement request signature integration
TrustlyInc/trustly-android-example pull request #7
Opened 2023-11-30 18:19 UTC by andresguedes

Adding code to show how to get a request signature from remote API

2023-11-30 19:21 UTC, marcosrivereto approved these changes

2023-12-05 14:42 UTC, renatodelpupo approved these changes

2023-12-06 00:39 UTC, lukevance requested changes
Andre, can you please add some details in the Readme.md file about this new feature and how to configure it? Something like this section in the webview example app: https://github.com/TrustlyInc/trustly-webview-example/blob/4adbfa6713848502616cac99d493b9ded293972b/react-web-app/README.md#server-side-features

Specifically, please note:
* to enable this feature, a user must setup this dependency and link to trustly-nestjs-example project
* Note where in the app this integration occurs (RetrofitClient.kt line 27)
* in the EstablishData.kt remove line 8 or note the reference of where this is generated dynamically
* Anything else the user might need to know to set this up and run it, I haven't been able to get very far because I'm stuck with a Java runtime error, which leads me to...

It appears that the project now requires a higher version of the Java runtime? Please correct me if I'm wrong, but I'm getting this error when I try to build the app: 

```Build file '/Users/lukevance/sandbox_dev/trustly-android-example/app/build.gradle' line: 2

An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Could not create an instance of type com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated.
      > Could not create an instance of type com.android.build.gradle.internal.dsl.LintImpl$AgpDecorated.
         > Could not generate a decorated class for type LintImpl$AgpDecorated.
            > com/android/tools/lint/model/LintModelSeverity has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

```

2023-12-06 01:15 UTC, lukevance requested changes
I'm not sure my project settings/Java/Gradle errors are related to the app itself. I think the main thing is the instructions for setup, it's important that a user can follow two paths:
1. simple quickstart: just run the project with no backend integration and no requestSignature
2. add security: later when they have solved this part, the user may want to revisit the project to understand how to setup requestSignatures

See the [AC here ](https://trustly.atlassian.net/browse/DEV-213519) that mentions "uncommenting" the logic, that may not be the right approach but the user should easily understand how to go from step 1 above to step 2.

2023-12-06 13:03 UTC, andresguedes commented on app/src/main/res/values/strings.xml
> +    <string name="app_name">TrustlySDKDemoAndroid</string>
👍🏽

2023-12-06 13:21 UTC, andresguedes commented on app/src/main/java/net/trustly/trustlysdkdemoandroid/ui/MainActivity.kt
> +                Toast.makeText(this, it.string(), Toast.LENGTH_SHORT).show()
This Toast is just to show the requestSignature to the user, but I'll change it and put in a Log for better DevX =)

2023-12-13 03:18 UTC, lukevance approved these changes
Awesome 😎

2023-12-13 03:18 UTC, lukevance commented on README.md
> +### Request Signature
👍 Looks good!

2024-01-09 17:24 UTC, merged